version: '3'

services:
  # 起動したコンテナに /bin/sh でアクセスする場合には以下のコマンドを実行する
  # docker exec -it mysql bash
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=xxxxxxxx
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./sample-webapp/src/main/resources/db/init/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

  # URL
  # http://localhost:9080/
  adminer:
    image: adminer:${ADMINER_VERSION}
    container_name: adminer
    restart: always
    ports:
      - 9080:8080
    environment:
      - TZ=Asia/Tokyo
      - ADMINER_DEFAULT_SERVER=mysql

  #############################################################################
  # Redis Cluster
  #
  # 起動したコンテナに /bin/sh でアクセスする場合には以下のコマンドを実行する
  # docker exec -it redis-cluster-6379 /bin/sh
  #
  # 起動したコンテナの redis に redis-cli でアクセスするには以下のコマンドを実行する
  # docker exec -it redis-cluster-6379 redis-cli -c
  #
  redis-cluster-1:
    image: redis:${REDIS_VERSION}-alpine
    container_name: redis-cluster-${REDIS_CLUSTER_1_PORT}
    ports:
      - "${REDIS_CLUSTER_1_PORT}:6379"
      - "1${REDIS_CLUSTER_1_PORT}:16379"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    command:
      - /bin/sh
      - -c
      - |
        redis-server /etc/redis/redis.conf \
                    --cluster-announce-ip ${HOST_IP_ADDRESS} \
                    --cluster-announce-port ${REDIS_CLUSTER_1_PORT} \
                    --cluster-announce-bus-port 1${REDIS_CLUSTER_1_PORT}
  redis-cluster-2:
    image: redis:${REDIS_VERSION}-alpine
    container_name: redis-cluster-${REDIS_CLUSTER_2_PORT}
    ports:
      - "${REDIS_CLUSTER_2_PORT}:6379"
      - "1${REDIS_CLUSTER_2_PORT}:16379"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    command:
      - /bin/sh
      - -c
      - |
        redis-server /etc/redis/redis.conf \
                    --cluster-announce-ip ${HOST_IP_ADDRESS} \
                    --cluster-announce-port ${REDIS_CLUSTER_2_PORT} \
                    --cluster-announce-bus-port 1${REDIS_CLUSTER_2_PORT}
    depends_on:
      - redis-cluster-1
  redis-cluster-3:
    image: redis:${REDIS_VERSION}-alpine
    container_name: redis-cluster-${REDIS_CLUSTER_3_PORT}
    ports:
      - "${REDIS_CLUSTER_3_PORT}:6379"
      - "1${REDIS_CLUSTER_3_PORT}:16379"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    command:
      - /bin/sh
      - -c
      - |
        redis-server /etc/redis/redis.conf \
                    --cluster-announce-ip ${HOST_IP_ADDRESS} \
                    --cluster-announce-port ${REDIS_CLUSTER_3_PORT} \
                    --cluster-announce-bus-port 1${REDIS_CLUSTER_3_PORT}
    depends_on:
      - redis-cluster-1
  redis-cluster-4:
    image: redis:${REDIS_VERSION}-alpine
    container_name: redis-cluster-${REDIS_CLUSTER_4_PORT}
    ports:
      - "${REDIS_CLUSTER_4_PORT}:6379"
      - "1${REDIS_CLUSTER_4_PORT}:16379"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    command:
      - /bin/sh
      - -c
      - |
        redis-server /etc/redis/redis.conf \
                    --cluster-announce-ip ${HOST_IP_ADDRESS} \
                    --cluster-announce-port ${REDIS_CLUSTER_4_PORT} \
                    --cluster-announce-bus-port 1${REDIS_CLUSTER_4_PORT}
    depends_on:
      - redis-cluster-1
  redis-cluster-5:
    image: redis:${REDIS_VERSION}-alpine
    container_name: redis-cluster-${REDIS_CLUSTER_5_PORT}
    ports:
      - "${REDIS_CLUSTER_5_PORT}:6379"
      - "1${REDIS_CLUSTER_5_PORT}:16379"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    command:
      - /bin/sh
      - -c
      - |
        redis-server /etc/redis/redis.conf \
                    --cluster-announce-ip ${HOST_IP_ADDRESS} \
                    --cluster-announce-port ${REDIS_CLUSTER_5_PORT} \
                    --cluster-announce-bus-port 1${REDIS_CLUSTER_5_PORT}
    depends_on:
      - redis-cluster-1
  redis-cluster-6:
    image: redis:${REDIS_VERSION}-alpine
    container_name: redis-cluster-${REDIS_CLUSTER_6_PORT}
    ports:
      - "${REDIS_CLUSTER_6_PORT}:6379"
      - "1${REDIS_CLUSTER_6_PORT}:16379"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
    command:
      - /bin/sh
      - -c
      - |
        redis-server /etc/redis/redis.conf \
                    --cluster-announce-ip ${HOST_IP_ADDRESS} \
                    --cluster-announce-port ${REDIS_CLUSTER_6_PORT} \
                    --cluster-announce-bus-port 1${REDIS_CLUSTER_6_PORT}
    depends_on:
      - redis-cluster-1
  redis-cluster-make:
    build:
      context: ./docker/redis
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    image: redis:${REDIS_VERSION}-custom
    container_name: redis-cluster-make
    environment:
      - TZ=Asia/Tokyo
    command:
      - /bin/sh
      - -c
      - |
        expect -c "
        spawn redis-cli --cluster create \
                          ${HOST_IP_ADDRESS}:${REDIS_CLUSTER_1_PORT} \
                          ${HOST_IP_ADDRESS}:${REDIS_CLUSTER_2_PORT} \
                          ${HOST_IP_ADDRESS}:${REDIS_CLUSTER_3_PORT} \
                          ${HOST_IP_ADDRESS}:${REDIS_CLUSTER_4_PORT} \
                          ${HOST_IP_ADDRESS}:${REDIS_CLUSTER_5_PORT} \
                          ${HOST_IP_ADDRESS}:${REDIS_CLUSTER_6_PORT} \
                        --cluster-replicas 1
        expect \"Can I set the above configuration? (type 'yes' to accept): \"
        send \"yes\n\"
        expect eof
        "
    depends_on:
      - redis-cluster-1
      - redis-cluster-2
      - redis-cluster-3
      - redis-cluster-4
      - redis-cluster-5
      - redis-cluster-6
